version: '3.8'

services:
  payment:
    image: payment.web:latest
    build:
      context: .
      dockerfile: ./services/payment/src/Payment.Web/Dockerfile
    ports:
      - "8082:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - LOG_FILE_PATH=/var/log/payment/log.txt
      - ConnectionStrings__PaymentWebDb=Host=db;Database=ikars;Username=postgres;Password=postgres
      - HttpClientSettings__TerminalServerBaseAddress=http://terminals:8082/
    volumes:
      - type: bind
        source: ./logs 
        target: /var/log/payment
    depends_on:
      - db
    networks:
      novikov:
        ipv4_address: 10.20.5.6
  
  terminals:
    build: ./services/terminals/src
    ports:
      - "3000:8082"
    networks:
      novikov:
        ipv4_address: 10.20.5.9
  
  statistic_web:
    image: nginx:alpine
    volumes:
      - ./services/statistic/web:/usr/share/nginx/html
    ports: 
      - "8080:80"
    networks:
      novikov:
        ipv4_address: 10.20.5.12

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ikars
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      novikov:
        ipv4_address: 10.20.5.3

volumes:
  postgres_data:
    
networks:
  novikov:
    driver: bridge
    ipam:
      config:
        - subnet: 10.20.5.0/24
