version: '3.8'

services:
  web:
    image: payment.web:latest
    build:
      context: .
      dockerfile: ./services/payment/src/Payment.Web/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - LOG_FILE_PATH=/var/log/payment/log.txt
      - ConnectionStrings__PaymentWebDb=Host=db;Database=ikars;Username=postgres;Password=postgres
    volumes:
      - type: bind
        source: ./logs 
        target: /var/log/payment
    depends_on:
      - db
    networks:
      novikov:
        ipv4_address: 10.20.5.6

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ikars
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      novikov:
        ipv4_address: 10.20.5.3

volumes:
  postgres_data:
    
networks:
  novikov:
    driver: bridge
    ipam:
      config:
        - subnet: 10.20.5.0/24
